# Notebook 01 — Data Profiling & Quality Assessment

1. Objectives
- Understand the datasets
- Assess data quality
- Identify issues before cleaning
- Produce profiling statistics

2. Imports & Configuration

In [28]:
import pandas as pd

3. Load Datasets

In [29]:
transactions=pd.read_csv(r"C:\Users\PCPRODZ\Desktop\energical-decision-platform\data\RawData\transactions_stage-V2.csv")
orders=pd.read_csv(r"C:\Users\PCPRODZ\Desktop\energical-decision-platform\data\RawData\orders_stage.csv")
customers=pd.read_csv(r"C:\Users\PCPRODZ\Desktop\energical-decision-platform\data\RawData\customers_stage-V2.csv")
catalogue=pd.read_csv(r"C:\Users\PCPRODZ\Desktop\energical-decision-platform\data\RawData\catalogue_stage_V3.csv")

In [30]:
datasets = {
    "Transactions": transactions,
    "Orders": orders,
    "Customers": customers,
    "Catalogue": catalogue,
}

4. Dataset Overview

-  Data shape, structure

In [32]:
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.shape)
    print(df.info())
    print(df.dtypes)

Transactions
(20405, 23)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20405 entries, 0 to 20404
Data columns (total 23 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   order_id_stage                    20405 non-null  object
 1   Code Client                       20405 non-null  object
 2   order_date                        20405 non-null  object
 3   wilaya_raw                        20405 non-null  object
 4   wilaya_normalized                 20405 non-null  object
 5   geo_quality_flag                  20405 non-null  object
 6   customer_type_inferred            20405 non-null  object
 7   sku                               20405 non-null  object
 8   product_name                      20267 non-null  object
 9   sku_quality                       20405 non-null  object
 10  category                          20405 non-null  object
 11  subcategory                       12895 non-null  object
 12  quantity                          20280 non-null  float64
 13  unit_price                        20280 non-null  float64
 14  line_total                        20280 non-null  float64
 15  order_status                      20405 non-null  object
 16  payment_method_group              20405 non-null  object
 17  Montant total de la commande      20405 non-null  object
 18  Titre moyen du paiement           20389 non-null  object
 19  sales_channel                     20405 non-null  object
 20  Titre de la méthode d’expédition  20321 non-null  object
 21  Poids total                       20405 non-null  float64
 22  Montant de l’expédition commande  20405 non-null  object
dtypes: float64(4), object(19)
memory usage: 3.6+ MB
None
order_id_stage                       object
Code Client                          object
order_date                           object
wilaya_raw                           object
wilaya_normalized                    object
geo_quality_flag                     object
customer_type_inferred               object
sku                                  object
product_name                         object
sku_quality                          object
category                             object
subcategory                          object
quantity                            float64
unit_price                          float64
line_total                          float64
order_status                         object
payment_method_group                 object
Montant total de la commande         object
Titre moyen du paiement              object
sales_channel                        object
Titre de la méthode d’expédition     object
Poids total                         float64
Montant de l’expédition commande     object
dtype: object

Orders
(9245, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9245 entries, 0 to 9244
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   order_id_stage          9245 non-null   object
 1   customer_id_stage       9245 non-null   object
 2   order_date              9245 non-null   object
 3   wilaya_raw              9245 non-null   object
 4   wilaya_normalized       9245 non-null   object
 5   customer_type_inferred  9245 non-null   object
 6   order_status            9245 non-null   object
 7   payment_method_group    9245 non-null   object
 8   sales_channel           9245 non-null   object
 9   order_total_amount      9245 non-null   float64
 10  total_quantity          9245 non-null   float64
 11  n_lines                 9245 non-null   int64
dtypes: float64(2), int64(1), object(9)
memory usage: 866.8+ KB
None
order_id_stage             object
customer_id_stage          object
order_date                 object
wilaya_raw                 object
wilaya_normalized          object
customer_type_inferred     object
order_status               object
payment_method_group       object
sales_channel              object
order_total_amount        float64
total_quantity            float64
n_lines                     int64
dtype: object

Customers
(5775, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5775 entries, 0 to 5774
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Code Client             5775 non-null   object
 1   customer_type_inferred  5775 non-null   object
 2   wilaya                  5775 non-null   object
 3   first_order_date        5775 non-null   object
 4   last_order_date         5775 non-null   object
 5   orders_count            5775 non-null   int64
 6   total_amount            5775 non-null   float64
 7   average_basket          5775 non-null   float64
dtypes: float64(2), int64(1), object(5)
memory usage: 361.1+ KB
None
Code Client                object
customer_type_inferred     object
wilaya                     object
first_order_date           object
last_order_date            object
orders_count                int64
total_amount              float64
average_basket            float64
dtype: object

Catalogue
(3850, 5)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3850 entries, 0 to 3849
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   SkU             3850 non-null   object
 1   Nom             3850 non-null   object
 2   categorie       3850 non-null   object
 3   Sous-catégorie  3849 non-null   object
 4   Prix unitaire   3632 non-null   float64
dtypes: float64(1), object(4)
memory usage: 150.5+ KB
None
SkU                object
Nom                object
categorie          object
Sous-catégorie     object
Prix unitaire     float64
dtype: object

5. Data profiling

- nulls

In [40]:
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.isnull().sum())

Transactions
order_id_stage                         0
Code Client                            0
order_date                             0
wilaya_raw                             0
wilaya_normalized                      0
geo_quality_flag                       0
customer_type_inferred                 0
sku                                    0
product_name                         138
sku_quality                            0
category                               0
subcategory                         7510
quantity                             125
unit_price                           125
line_total                           125
order_status                           0
payment_method_group                   0
Montant total de la commande           0
Titre moyen du paiement               16
sales_channel                          0
Titre de la méthode d’expédition      84
Poids total                            0
Montant de l’expédition commande       0
dtype: int64

Orders
order_id_stage            0
customer_id_stage         0
order_date                0
wilaya_raw                0
wilaya_normalized         0
customer_type_inferred    0
order_status              0
payment_method_group      0
sales_channel             0
order_total_amount        0
total_quantity            0
n_lines                   0
dtype: int64

Customers
Code Client               0
customer_type_inferred    0
wilaya                    0
first_order_date          0
last_order_date           0
orders_count              0
total_amount              0
average_basket            0
dtype: int64

Catalogue
SkU                 0
Nom                 0
categorie           0
Sous-catégorie      1
Prix unitaire     218
dtype: int64

- Duplicates

In [41]:
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.duplicated().sum())
    print(df.nunique())

Transactions
12
order_id_stage                      9241
Code Client                         5775
order_date                          1531
wilaya_raw                            60
wilaya_normalized                     59
geo_quality_flag                       4
customer_type_inferred                 2
sku                                  732
product_name                        1351
sku_quality                            4
category                               4
subcategory                           43
quantity                             124
unit_price                          1787
line_total                          3621
order_status                           9
payment_method_group                   5
Montant total de la commande        4853
Titre moyen du paiement               17
sales_channel                          1
Titre de la méthode d’expédition     107
Poids total                         2392
Montant de l’expédition commande     128
dtype: int64

Orders
0
order_id_stage            9245
customer_id_stage         4946
order_date                1531
wilaya_raw                  60
wilaya_normalized           59
customer_type_inferred       4
order_status                 9
payment_method_group         5
sales_channel                1
order_total_amount        3976
total_quantity             192
n_lines                     38
dtype: int64

Customers
0
Code Client               5775
customer_type_inferred       2
wilaya                      57
first_order_date          1454
last_order_date           1409
orders_count                36
total_amount              3011
average_basket            3035
dtype: int64

Catalogue
93
SkU               3754
Nom               3755
categorie            3
Sous-catégorie      55
Prix unitaire      437
dtype: int64

In [35]:
catalogue[catalogue.duplicated()]

,SkU,Nom,categorie,Sous-catégorie,Prix unitaire
12,SKU-27803,Baguette de vitre,Menuiserie,Portes > Accessoires Portes,450.0
79,SKU-33813,Cadre de porte,Menuiserie,Portes,15000.0
80,SKU-33813,Cadre de porte,Menuiserie,Portes,15000.0
81,SKU-33813,Cadre de porte,Menuiserie,Portes,15000.0
82,SKU-33813,Cadre de porte,Menuiserie,Portes,15000.0
...,...,...,...,...,...
581,SKU-33814,Ouvrant de porte,Menuiserie,Portes,30000.0
582,SKU-33814,Ouvrant de porte,Menuiserie,Portes,30000.0
583,SKU-33814,Ouvrant de porte,Menuiserie,Portes,30000.0
611,SKU-28789,Poignée avec clé,Menuiserie,Portes > Accessoires Portes,2500.0
3685,SKU-28229,Rallonges 6,Menuiserie,Portes > Accessoires Portes,1900.0

In [36]:
catalogue[catalogue["SkU"].isnull()]

Empty DataFrame
Columns: [SkU, Nom, categorie, Sous-catégorie, Prix unitaire]
Index: []

- Descriptive statistics

In [37]:
for name, df in datasets.items():
    print(f"\n{name}")
    print(df.describe(include="all"))

Transactions
       order_id_stage  Code Client  order_date wilaya_raw wilaya_normalized  \
count           20405        20405       20405      20405             20405
unique           9241         5775        1531         60                59
top       CMD_S008870  CLT_S002151  2026-06-17      Alger             Alger
freq               57          160         115       4656              4656
mean              NaN          NaN         NaN        NaN               NaN
std               NaN          NaN         NaN        NaN               NaN
min               NaN          NaN         NaN        NaN               NaN
25%               NaN          NaN         NaN        NaN               NaN
50%               NaN          NaN         NaN        NaN               NaN
75%               NaN          NaN         NaN        NaN               NaN
max               NaN          NaN         NaN        NaN               NaN

       geo_quality_flag customer_type_inferred          sku  \
count             20405                  20405        20405
unique                4                      2          732
top                  ok                    B2C  SKU-INCONNU
freq              20003                  18783         4254
mean                NaN                    NaN          NaN
std                 NaN                    NaN          NaN
min                 NaN                    NaN          NaN
25%                 NaN                    NaN          NaN
50%                 NaN                    NaN          NaN
75%                 NaN                    NaN          NaN
max                 NaN                    NaN          NaN

                                             product_name sku_quality  ...  \
count                                               20267       20405  ...
unique                                               1351           4  ...
top     Protecteur de tension et courant réglable PTDR...          ok  ...
freq                                                  389       12799  ...
mean                                                  NaN         NaN  ...
std                                                   NaN         NaN  ...
min                                                   NaN         NaN  ...
25%                                                   NaN         NaN  ...
50%                                                   NaN         NaN  ...
75%                                                   NaN         NaN  ...
max                                                   NaN         NaN  ...

           unit_price    line_total  order_status  payment_method_group  \
count    20280.000000  2.028000e+04         20405                 20405
unique            NaN           NaN             9                     5
top               NaN           NaN      Terminée        À_la_livraison
freq              NaN           NaN         19524                 18394
mean      9409.861750  1.604904e+04           NaN                   NaN
std      23738.292687  9.407205e+04           NaN                   NaN
min      -4725.000000 -1.396500e+04           NaN                   NaN
25%        472.000000  1.150000e+03           NaN                   NaN
50%       1735.000000  3.580000e+03           NaN                   NaN
75%       6580.000000  1.016150e+04           NaN                   NaN
max     222000.000000  9.940000e+06           NaN                   NaN

        Montant total de la commande  Titre moyen du paiement sales_channel  \
count                          20405                    20389         20405
unique                          4853                       17             1
top                          0.00 DA  Paiement à la livraison           web
freq                             409                    16932         20405
mean                             NaN                      NaN           NaN
std                              NaN                      NaN           NaN
min                              NaN                      NaN           NaN
25%                              NaN                      NaN           NaN
50%                              NaN                      NaN           NaN
75%                              NaN                      NaN           NaN
max                              NaN                      NaN           NaN

       Titre de la méthode d’expédition  Poids total  \
count                             20321  20405.00000
unique                              107          NaN
top                    Point de retrait          NaN
freq                               5820          NaN
mean                                NaN     11.11894
std                                 NaN     54.23383
min                                 NaN      0.00000
25%                                 NaN      0.24900
50%                                 NaN      1.97760
75%                                 NaN      8.00000
max                                 NaN   3640.00000

       Montant de l’expédition commande
count                             20405
unique                              128
top                             0.00 DA
freq                               7793
mean                                NaN
std                                 NaN
min                                 NaN
25%                                 NaN
50%                                 NaN
75%                                 NaN
max                                 NaN

[11 rows x 23 columns]

Orders
       order_id_stage customer_id_stage  order_date wilaya_raw  \
count            9245              9245        9245       9245
unique           9245              4946        1531         60
top       CMD_S000001        CLT_S03655  2026-07-18      Alger
freq                1              1381          29       2299
mean              NaN               NaN         NaN        NaN
std               NaN               NaN         NaN        NaN
min               NaN               NaN         NaN        NaN
25%               NaN               NaN         NaN        NaN
50%               NaN               NaN         NaN        NaN
75%               NaN               NaN         NaN        NaN
max               NaN               NaN         NaN        NaN

       wilaya_normalized customer_type_inferred order_status  \
count               9245                   9245         9245
unique                59                      4            9
top                Alger                    B2C     Terminée
freq                2299                   8658         8807
mean                 NaN                    NaN          NaN
std                  NaN                    NaN          NaN
min                  NaN                    NaN          NaN
25%                  NaN                    NaN          NaN
50%                  NaN                    NaN          NaN
75%                  NaN                    NaN          NaN
max                  NaN                    NaN          NaN

       payment_method_group sales_channel  order_total_amount  total_quantity  \
count                  9245          9245        9.245000e+03     9245.000000
unique                    5             1                 NaN             NaN
top          À_la_livraison           web                 NaN             NaN
freq                   8433          9245                 NaN             NaN
mean                    NaN           NaN        3.527169e+04       10.416009
std                     NaN           NaN        1.510075e+05       70.932861
min                     NaN           NaN        0.000000e+00        0.000000
25%                     NaN           NaN        3.329000e+03        1.000000
50%                     NaN           NaN        9.780000e+03        2.000000
75%                     NaN           NaN        2.919300e+04        5.000000
max                     NaN           NaN        9.940000e+06     4943.000000

            n_lines
count   9245.000000
unique          NaN
top             NaN
freq            NaN
mean       2.194808
std        2.744219
min        0.000000
25%        1.000000
50%        1.000000
75%        2.000000
max       57.000000

Customers
        Code Client customer_type_inferred wilaya first_order_date  \
count          5775                   5775   5775             5775
unique         5775                      2     57             1454
top     CLT_S000001                    B2C  Alger        7/18/2026
freq              1                   5614   1469               18
mean            NaN                    NaN    NaN              NaN
std             NaN                    NaN    NaN              NaN
min             NaN                    NaN    NaN              NaN
25%             NaN                    NaN    NaN              NaN
50%             NaN                    NaN    NaN              NaN
75%             NaN                    NaN    NaN              NaN
max             NaN                    NaN    NaN              NaN

       last_order_date  orders_count  total_amount  average_basket
count             5775   5775.000000  5.775000e+03    5.775000e+03
unique            1409           NaN           NaN             NaN
top          7/18/2026           NaN           NaN             NaN
freq                27           NaN           NaN             NaN
mean               NaN      1.600173  5.635923e+04    3.605025e+04
std                NaN      2.560112  2.584612e+05    1.673031e+05
min                NaN      1.000000  0.000000e+00    0.000000e+00
25%                NaN      1.000000  4.300000e+03    3.930000e+03
50%                NaN      1.000000  1.726300e+04    1.232690e+04
75%                NaN      1.000000  3.950450e+04    3.000000e+04
max                NaN     76.000000  1.073048e+07    9.940000e+06

Catalogue
              SkU             Nom   categorie Sous-catégorie  Prix unitaire
count        3850            3850        3850           3849    3632.000000
unique       3754            3755           3             55            NaN
top     SKU-33813  Cadre de porte  Menuiserie         Portes            NaN
freq           51              51        3072           2987            NaN
mean          NaN             NaN         NaN            NaN   27913.689703
std           NaN             NaN         NaN            NaN   15453.969753
min           NaN             NaN         NaN            NaN       0.000000
25%           NaN             NaN         NaN            NaN   25000.000000
50%           NaN             NaN         NaN            NaN   30500.000000
75%           NaN             NaN         NaN            NaN   35000.000000
max           NaN             NaN         NaN            NaN  198000.000000

- Business Integrity Checks

- transactions

In [38]:
#negative quantity
negative_quantity = transactions[transactions["quantity"] < 0]
print(f"Negative quantities: {len(negative_quantity)}")
negative_quantity.head()
#negative price
negative_price = transactions[transactions["unit_price"]<0]
print(f"Negative prices: {len(negative_price)}")
negative_price.head()
#negative_line_totals
negative_total = transactions[transactions["line_total"] < 0]
print(f"Negative line totals: {len(negative_total)}")
negative_total.head()
#future order
transactions["order_date"] = pd.to_datetime(
    transactions["order_date"],
    errors="coerce"
)
future_date=transactions[transactions["order_date"] > pd.Timestamp.today()]
print(f"Future dates:{len(future_date)}")

Negative quantities: 0
Negative prices: 65
Negative line totals: 65
Future dates:0

## Key findings
- ### Dataset Quality
- All four datasets were successfully loaded and inspected.
- No missing values were detected in the Orders and Customers datasets.
- Most columns were imported as object and require data type standardization (dates, text, and categorical variables).
- ### Missing Values
- #### Transactions
- 138  missing product_name values.
- 7510  missing subcategory values.
- 125 missing values in quantity, unit_price, and line_total.
- #### Catalogue
- 218 missing unit_price values.
- 2819 missing SKU values
- 93 duplicates.
- ### Duplicate Records
- 12 duplicate rows were detected in the Transactions dataset.
(These records require further investigation to determine whether they are true duplicates or valid business records.)
- ### Business Rule Validation
- No negative quantities were found.
- 65 records contain negative unit_price values.
- The same 65 records also contain negative line_total values, suggesting they may represent refunds, returns, or accounting adjustments rather than data entry errors.
- ### Initial Observations
- The 125 transaction records with missing financial information appear to correspond to zero-value orders and will require a business decision before cleaning.